@FacilAssist.API_HostAddress = http://localhost:5206

GET {{FacilAssist.API_HostAddress}}/api/clientes
Accept: application/json

###

POST {{FacilAssist.API_HostAddress}}/api/clientes
Content-Type: application/json

{
  "nome": "Cliente Teste",
  "cpf": "52998224725",
  "dataNascimento": "1990-01-01",
  "sexo": "M",
  "situacaoClienteId": 1
}

###

PUT {{FacilAssist.API_HostAddress}}/api/clientes/1
Content-Type: application/json

{
  "nome": "Cliente Teste Atualizado",
  "cpf": "52998224725",
  "dataNascimento": "1990-01-01",
  "sexo": "M",
  "situacaoClienteId": 1
}

###

DELETE {{FacilAssist.API_HostAddress}}/api/clientes/1
Accept: application/json
